server:
  port: 8091
  tomcat:
    # Spring Boot 2.3: 设置服务器工作线程
    threads:
      max: 120
    # Spring Boot 2.4: Configure how long Tomcat will wait for another request before closing a keep-alive connection.
    keep-alive-timeout: 30s
    # Spring Boot 2.4: Control the maximum number of requests that can be made on a keep-alive connection before it is closed
    max-keep-alive-requests: 120

spring:
  config:
    # Spring Boot 2.4: 根据当前环境变量来激活当前配置
    activate:
      on-profile: dev
    # Spring Boot 2.4: 导入数据配置文件给当前配置
    import: "classpath:develop.properties"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # sundial可以使用druid数据源
    #druid:
      #url: ${mysql.url}
      #username: ${mysql.user}
      #password: ${MYSQL_PWD}
    url: ${mysql.url}
    username: ${mysql.user}
    password: ${MYSQL_PWD}
    hikari:
      pool-name: hk_dbcp
      # 等待从连接池获取连接时间（默认30s）
      connection-timeout: 60000
      maximum-pool-size: 30
      minimum-idle: 5
      # 连接在池中闲置时间，最低设置为10s，0代表不会从连接池中移除（默认为10分钟）
      idle-timeout: 120000
      # 在连接池最大存活时间，0代表无限生命时间，最低设置为30s（默认为30分钟）
      # 该设置不作用在正使用的连接，除非调用了连接关闭
      max-lifetime: 1800000
      # 连接激活的保持时间，该事件只会发生在闲置连接，到期会从池中移除，最低设置为30s，设置为1分钟内最佳
      keepalive-time: 35000

  redis:
    host: 127.0.0.1
    # Spring Boot 2.7: Support for specifying a username for authenticating to Sentinel(s)
    #sentinel:
      #username:

  # Spring Boot 2.6: To use embedded mongo, the spring.mongodb.embedded.version property must now be set.
  #mongodb:
    #embedded:
      #version: 3.6

  data:
    mongodb:
      database: milkomeda
      host: localhost
      port: 27017


  # Pulsar模块异步线程池（Async异步任务线程池，Spring Boot 2.1.0+在这里配置）
  task:
    execution:
      thread-name-prefix: pulsar-
      pool:
        queue-capacity: 150
        core-size: 8
        max-size: 12
        keep-alive: 100s

    # Ice模块的调度线程池（Spring Task调度线程池，Spring Boot 2.1.0+在这里配置）
    scheduling:
      thread-name-prefix: ice-
      pool:
        size: 20
      shutdown:
        await-termination: true
        await-termination-period: 60s

  quartz:
    scheduler-name: neutron
    overwrite-existing-jobs: true
    wait-for-jobs-to-complete-on-shutdown: true

mybatis:
  type-aliases-package: com.github.yizzuide.milkomeda.demo.halo.domain
  mapper-locations:
    - classpath*:mapper/*.xml
  config-location: classpath:config/mybatis-config.xml

logging:
  level:
    com.github.yizzuide.milkomeda.demo.sundial.mapper: DEBUG
    com.github.yizzuide.milkomeda.ice.inspector.mapper: DEBUG
  # Spring Boot 2.4: The charsets used to by Logback and Log4j logging can now be configured
  charset:
    console: UTF-8
    file: UTF-8

management:
  server:
    port: 9000
  endpoint:
    shutdown:
      enabled: false
    health:
      show-details: always
    # Spring Boot 2.4: A new startup actuator endpoint is now available that shows information about your application startup.
    startup:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  # Spring Boot 2.4: HTTP traces no longer include cookie headers by default.
  #trace:
    #http:
      #include: cookies, errors, request-headers, response-headers
  info:
    # Spring Boot 2.6: The env info contributor is now disabled by default. It would like them to appear them in the InfoEndpoint.
    env:
      enabled: true
    # Spring Boot 2.6: Expose Java Runtime information under the java key.
    java:
      enabled: true
    # Spring Boot 2.7: An OsInfoContributor can expose some information about the Operating System the application is running on.
    os:
      enabled: on
