server:
  # Spring Boot 2.6: spring.webflux.session property group move to server.reactive.session
  reactive:
    session:
      timeout: 120m
      cookie:
        http-only: true
        name: mk-sessionId
  servlet:
    session:
      timeout: 120m
      cookie:
        http-only: true
        # 自定义sessionId，用于后台登录唯一标识，防止被第三方平台覆盖
        name: mk-sessionId
        # Spring Boot 2.6: SameSite Cookie Attribute Servlet Support
        same-site: lax # strict: 完全禁止第三方获取cookie lax: 第三方请求只有<a|link href='xxx'>和GET表单发送Cookie none: 只能通过https发送
    # Spring Boot 2.4: No longer register the DefaultServlet provided by your servlet container.
    register-default-servlet: true
    # Spring Boot 2.3: 设置服务器编码
    encoding:
      charset: UTF-8
  # Spring Boot 2.3: 优雅关机，拒绝新请求，等正在执行的请求完成
  shutdown: graceful
  # Spring Boot 2.3: 不再响应默认的错误信息
  error:
    include-binding-errors: never
    include-message: never
    include-stacktrace: never
    # Spring Boot 3.0: 配置异常转发路径时，过滤器可通过设置ERROR类型触发<code>filter.setDispatcherTypes(DispatcherType.ERROR);</code>
    path: /error
  # Spring Boot 2.7: Embedded web servers can be configured to use SSL with PEM-encoded certificate and private key files
  #  Management endpoints can be secured using similar management.server.ssl.* properties
  #ssl:
    #certificate:
    #certificate-private-key:



spring:
  # Spring Boot 2.3: 优雅关机等待时间
  lifecycle:
    timeout-per-shutdown-phase: 20s
  main:
    # Spring Boot 2.1: Bean重复定义是否覆盖
    allow-bean-definition-overriding: false
    # Spring Boot 2.6: Circular references between beans are now prohibited by default.
    #allow-circular-references: true
  web:
    # Spring Boot 2.4: 资源不生成mapping映射
    resources:
      add-mappings: false
  mvc:
    # 异步超时
    async:
      request-timeout: 20s

    # Spring Boot 2.6: 默认的路径匹配器由AntPathMatcher改为PathPatternParser（包括Actuator，但matching-strategy不作用于Actuator），匹配根路径必须添加"/"
    #pathmatch:
      #matching-strategy: ant_path_matcher

    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss

  # 国际化资源位置
  messages:
    basename: i18n/messages

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
    time-zone: GMT+8

  # Spring Boot 3.0: In Servlet applications, Spring Security 6.0 applies authorization to every dispatch type.
  #   To align with this, Spring Boot now configures Spring Security’s filter to be called for every dispatch type.
  security:
    filter:
      dispatcher-types: async, error, forward, include, request

  # Spring Boot 3.2：开启虚拟线程
  threads:
    virtual:
      enabled: true